# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Midwinter Days
description: >- # this means to ignore newlines until "baseurl:"
  웹 개발 공부하는 블로그
baseurl: "" # the subpath of the site
url: "https://fadonoey.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: About Me
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: happy_tjdus@naver.com
      link: mailto:happy_tjdus@naver.com


  follow:
    - name: Instagram
      link: https://www.instagram.com/daisydreamn/
      username: "@daisydreamn"
    - name: GitHub
      link: http://github.com/fadonoey


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

theme: jekyll-theme-cayman
